export { default as AddProduct } from './AddProduct'
export { default as ProductDetail } from './ProductDetail'
export { default as ProductList } from './ProductList'
export { default as EditProduct } from './EditProduct'
export { default as Header } from './Header'